[package]
name = "merkle_tree_rust"
version = "0.1.0"
authors = ["livelybug <livelybug@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.0"
hex = "0.4.2"
rand = "0.7.3"